### PR TITLE
 Enable use of ~ instead of $HOME in rcrc 

### PR DESCRIPTION
**Pull request by rmeritz**
https://github.com/thoughtbot/rcm/issues/218

### CODE REVIEW

**Comment by mike-burns** [comment]
(enhancement because it adds a few, bug because it has a second commit that fixes the contributing docs.)

**Comment by fgtham** [comment]
I think the root cause is a problem in `is_relative`:

https://github.com/thoughtbot/rcm/blob/09539fa521fd22442e8d58123529059234dc470d/share/rcm.sh.in#L54

It checks wether a given path is relative or not by looking at its first character. Unfortunately,  it doesn't do tilde expansion first. A path `~/.dotfiles` is incorrectly assumed to be relative, because it has no leading slash.

The fix proposed in the PR has two shortcomings:

* It fixes tilde expansion for `DOTFILE_DIRS`, but not for `EXCLUDES`, `SYMLINK_DIRS`, `UNDOTTED`.
* A tilde prefix consists of a `~` character followed by a login name, which may be null (the common case). The fix only takes into account the common case; `~foo/.dotfiles` would still not work.

A possible fix to `is_relative` might be:
* `is_relative() { eval echo "$1" | grep -v '^/' >/dev/null }`
* `is_relative() { [[ -n "${1%%/*}" ]] }` -- tilde expansion is performed inside `[[ ]]`
* `is_relative() { [[ "${1:0:1}" = ':' ]] }` -- probably not, because not every shell has substring expansion

What do you think?

**Comment by mike-burns** [comment]
Is `[[` POSIX?

I was looking for a simple command that expands `~` correctly -- is `eval` that command?

**Comment by fgtham** [comment]
No, `[[` is not POSIX. Furthermore, my two "solutions" above using `[[` do not work -- I messed up my tests :-1: 

The first one, using `eval`, works correctly. Maybe it is what you want?

**Comment by mike-burns** [comment]
I wouldn't consider `~/dotfiles` to be a relative path, so modifying `is_relative` doesn't make a ton of sense to me. I do like the `eval echo` solution to the problem, though.

Anything after the `is_relative` conditional block should assume that `$DOTFILES_DIR` is a complete, absolute, direct pathname. I think modifying `DOTFILES_DIR` makes sense for that.

**Comment by mike-burns** [comment]
The issue with `COPY_ALWAYS`, `EXCLUDES`, `SYMLINK_DIRS`, and `UNDOTTED` is that they can contain globs. We want to expand `~` and e.g. `~dmr` but not `*`.

(Note that this is a pervasive problem across the codebase and that all the patterns tend to break somewhere ...)

Let's leave this PR for just `DOTFILES_DIRS`, due to the complexity of applying to across the patterns.

**Comment by mike-burns** [comment]
This is merged into `master` as 95e6ca15aabd71ac1709ddb5e10e3baa11eeee66, d2e4daba376dcb96c1cad5fd89413f154a8c4a10, and c5574e7b514706b514602925691d3d9eed9f2bcb.

**Pull request closed without merging**
