### PR TITLE
Move from ruby to python for mustache

### PR DESCRIPTION
**Pull request by mat-m**
* Use pystache module
* Rewrite autocontrib
* Update CONTRIBUTING
* Fix all Markdown files by linting

Goal is to lower the number of dependencies.

### CODE REVIEW

**Comment by mike-burns** [comment]
OK so first off, thoughtbot is a Ruby on Rails consultancy, so this is going to be a tough dependency for me to be excited about.

But secondly, we don't currently have a Python dependency, right? So this would be swapping a Ruby one for a Python one?

**Comment by mat-m** [comment]
> OK so first off, thoughtbot is a Ruby on Rails consultancy, so this is going to be a tough dependency for me to be excited about.
> 
I acknowledge that. :)

> But secondly, we don't currently have a Python dependency, right? So this would be swapping a Ruby one for a Python one?
We need python for tests, actually.

BTW, this was an attempt to also dig in python and find a mustache module, because I find it elegant. If you want to stay this way, no prob.

**Comment by mat-m** [comment]
> But secondly, we don't currently have a Python dependency, right? So this would be swapping a Ruby one for a Python one?

Python is required for running the tests, as cram runs with python.

A good exercise would also be to move out from perl's cwd and use python's `os.path.realpath()`

**Comment by mike-burns** [comment]
> Python is required for running the tests, as cram runs with python.

Dang, you got me. OK!

**Comment by mike-burns** [comment]
Merged as 20e32cadfd282a9dfdf691186b6d323bf22bd810. Thank you as always!

**Pull request closed without merging**
