### PR TITLE
Fixing mkrc-one-dotfile-arg test to address newly allowed args

### PR DESCRIPTION
**Pull request by alexg0**

### CODE REVIEW

**Comment by alexg0** [comment]
Any concerns with merging this.  Just fixes broken test case.

**Comment by alexg0** [comment]
@mat-m Incorporated your suggestion to make the test more resilient to usage text changes.

**Comment by teoljungberg** [comment]
I also ran into this while running the test suite locally,

```
=================================
   rcm 1.3.4: ./test-suite.log
=================================

# TOTAL: 44
# PASS:  43
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/mkrc-one-dotfile-arg.t
=================================

!
--- test/mkrc-one-dotfile-arg.t
+++ test/mkrc-one-dotfile-arg.t.err
@@ -13,7 +13,7 @@

   $ mkrc -d .dotfiles -d .other-dotfiles rcfile
   Only one '-d' option is allowed in mkrc.
-  Usage: mkrc [-ChSsUuVvqo] [-t TAG] [-d DIR] [-B HOSTNAME] FILES ...
+  Usage: mkrc [-ChSsUuVvqokK] [-t TAG] [-d DIR] [-B HOSTNAME] FILES ...
   see mkrc(1) and rcm(7) for more details
   [64]


# Ran 1 tests, 0 skipped, 1 failed.
FAIL test/mkrc-one-dotfile-arg.t (exit status: 1)

```

@mike-burns Is there anything we can do to get this upstreamed?

**Comment by mike-burns** [comment]
Thanks for the ping. I'll try to get to this on Friday.

**Comment by teoljungberg** [comment]
I can raise a new PR that adds all flags to the test, if that's warranted instead of this wildcard approach.

**Comment by mike-burns** [comment]
Thank you for this.

You had advanced autoconf to 2.71, but Debian stable is still on 2.69 so I had to undo that to get it to work. Debian testing has 2.71 so hopefully we can switch to that next year.

**Pull request merged**
